[package]
name = "ffmpeg-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
futures-lite = "1.13.0"
tempfile = "3.6.0"
tokio = { version = "1.29.1", features = ["net", "io-util", "process", "rt", "sync", "macros"] }

[dev-dependencies]
tokio-test = "0.4.2"
